org: shinobushiva
app: myapp
service: company-logo-share-server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  stage: dev
  # vpc:
  #   securityGroupIds:
  #     - ${env:SECURITY_GROUP_IDS} # your security group id
  #   subnetIds:
  #     - ${env:SUBNET_IDS} # your subnet id
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - "ec2:CreateNetworkInterface"
  #       - "ec2:DescribeNetworkInterfaces"
  #       - "ec2:DeleteNetworkInterface"
  #     Resource:
  #       - "*"
  ecr:
    images:
      scanOnPush: true
      appimage:
        path: ./

functions:
  ${file(./serverless/functions${env:OFFLINE_EXT, ''}.yml):functions}

plugins:
  - serverless-offline

# custom:
#   webpack:
#     includeModules: true

package:
  exclude:
    - .git
    - .gitignore
    - docker.env
    - docker.env.sample
    - docker-compose.yml
    - Dockerfile.dev
