org: shinobushiva
app: myapp
service: company-logo-share-server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  stage: dev
  vpc:
    securityGroupIds:
      # - ${env:SECURITY_GROUP_IDS} # your security group id
      - sg-05ba04822d3d0d57b
    subnetIds:
      # - ${env:SUBNET_IDS} # your subnet id
      - subnet-0c0f58e41094528a9
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
      Resource:
        - "*"
  ecr:
    images:
      scanOnPush: true
      appimage:
        path: ./

functions:
  ${file(./serverless/functions${env:OFFLINE_EXT, ''}.yml):functions}

plugins:
  - serverless-offline
  - serverless-plugin-lambda-insights

# custom:
#   webpack:
#     includeModules: true

package:
  exclude:
    - .git
    - .gitignore
    - docker.env
    - docker.env.sample
    - docker-compose.yml
    - Dockerfile.dev
